"""
Configuration for TextKomplexitaet analyzer.

Thresholds and settings for complexity detection.
"""

from dataclasses import dataclass
from typing import Dict, Optional


@dataclass
class ComplexityConfig:
    """Configuration for complexity analysis."""

    # Model settings
    model_name: str = "MiriUll/distilbert-german-text-complexity"
    device: str = "cpu"  # "cpu" or "cuda"

    # Complexity thresholds (1-7 scale from the model)
    # 1 = very simple, 7 = very complex
    simple_threshold: float = 2.5  # Below this = simple
    medium_threshold: float = 4.0  # Below this = medium, above = complex

    # Word-level detection settings
    word_ablation_threshold: float = 0.5  # Min complexity change to flag word
    min_word_length: int = 3  # Skip very short words

    # Performance settings
    cache_model: bool = True
    batch_size: int = 8

    # Output settings
    include_suggestions: bool = True
    max_suggestions: int = 3


# Default configuration
DEFAULT_CONFIG = ComplexityConfig()

# Strict configuration (more sensitive)
STRICT_CONFIG = ComplexityConfig(
    simple_threshold=2.0, medium_threshold=3.5, word_ablation_threshold=0.3
)

# Lenient configuration (less sensitive)
LENIENT_CONFIG = ComplexityConfig(
    simple_threshold=3.0, medium_threshold=4.5, word_ablation_threshold=0.7
)


# Known simple words that should never be flagged
# These are common German words that appear frequently in Leichte Sprache
SIMPLE_WORDS_WHITELIST = {
    # Articles and determiners
    "der",
    "die",
    "das",
    "ein",
    "eine",
    "einer",
    "einem",
    "einen",
    "dieser",
    "diese",
    "dieses",
    "jeder",
    "jede",
    "jedes",
    "kein",
    "keine",
    "keiner",
    "keinem",
    "keinen",
    "mein",
    "meine",
    "dein",
    "deine",
    "sein",
    "seine",
    "ihr",
    "ihre",
    "unser",
    "unsere",
    "euer",
    "eure",
    # Pronouns
    "ich",
    "du",
    "er",
    "sie",
    "es",
    "wir",
    "mich",
    "dich",
    "sich",
    "uns",
    "euch",
    "mir",
    "dir",
    "ihm",
    "ihnen",
    "man",
    "jemand",
    "niemand",
    "alle",
    "alles",
    # Common nouns (concrete, everyday)
    "haus",
    "zimmer",
    "tisch",
    "stuhl",
    "bett",
    "tür",
    "fenster",
    "auto",
    "bus",
    "zug",
    "fahrrad",
    "straße",
    "weg",
    "wasser",
    "brot",
    "essen",
    "trinken",
    "mann",
    "frau",
    "kind",
    "mensch",
    "leute",
    "familie",
    "freund",
    "freundin",
    "mutter",
    "vater",
    "eltern",
    "arzt",
    "schule",
    "arbeit",
    "geld",
    "zeit",
    "tag",
    "nacht",
    "stadt",
    "land",
    "ort",
    "platz",
    "hund",
    "katze",
    "tier",
    "baum",
    "blume",
    "buch",
    "brief",
    "bild",
    "telefon",
    "computer",
    # Common verbs
    "haben",
    "werden",
    "können",
    "müssen",
    "sollen",
    "wollen",
    "dürfen",
    "machen",
    "tun",
    "gehen",
    "kommen",
    "fahren",
    "laufen",
    "sagen",
    "sprechen",
    "fragen",
    "antworten",
    "erzählen",
    "sehen",
    "hören",
    "fühlen",
    "denken",
    "wissen",
    "verstehen",
    "geben",
    "nehmen",
    "bringen",
    "holen",
    "legen",
    "stellen",
    "setzen",
    "kaufen",
    "verkaufen",
    "bezahlen",
    "kosten",
    "arbeiten",
    "lernen",
    "lesen",
    "schreiben",
    "spielen",
    "schlafen",
    "wohnen",
    "leben",
    "helfen",
    "brauchen",
    "suchen",
    "finden",
    "beginnen",
    "anfangen",
    "aufhören",
    "enden",
    "öffnen",
    "schließen",
    "warten",
    # Common adjectives
    "gut",
    "schlecht",
    "schön",
    "hässlich",
    "groß",
    "klein",
    "lang",
    "kurz",
    "hoch",
    "tief",
    "neu",
    "alt",
    "jung",
    "schnell",
    "langsam",
    "früh",
    "spät",
    "viel",
    "viele",
    "wenig",
    "wenige",
    "mehr",
    "weniger",
    "wichtig",
    "richtig",
    "falsch",
    "einfach",
    "schwer",
    "leicht",
    "schwierig",
    "warm",
    "kalt",
    "heiß",
    "hell",
    "dunkel",
    "laut",
    "leise",
    "nah",
    "weit",
    "nächste",
    "letzte",
    "erste",
    # Common adverbs
    "hier",
    "dort",
    "da",
    "wo",
    "wohin",
    "woher",
    "jetzt",
    "heute",
    "morgen",
    "gestern",
    "bald",
    "später",
    "immer",
    "nie",
    "oft",
    "manchmal",
    "selten",
    "sehr",
    "ganz",
    "ziemlich",
    "etwas",
    "fast",
    "auch",
    "noch",
    "schon",
    "nur",
    "erst",
    "ja",
    "nein",
    "nicht",
    "vielleicht",
    "warum",
    "weil",
    "deshalb",
    "darum",
    # Prepositions
    "in",
    "an",
    "auf",
    "unter",
    "über",
    "vor",
    "hinter",
    "neben",
    "zwischen",
    "mit",
    "ohne",
    "für",
    "gegen",
    "um",
    "durch",
    "von",
    "zu",
    "nach",
    "bei",
    "aus",
    "seit",
    "bis",
    # Conjunctions
    "und",
    "oder",
    "aber",
    "sondern",
    "denn",
    "wenn",
    "als",
    "ob",
    "dass",
    "obwohl",
    # Numbers
    "eins",
    "zwei",
    "drei",
    "vier",
    "fünf",
    "sechs",
    "sieben",
    "acht",
    "neun",
    "zehn",
    "hundert",
    "tausend",
    "million",
}


# Known complex words with suggestions
# Format: {"complex_word": {"simple": "suggestion", "category": "category"}}
COMPLEX_WORDS_WITH_SUGGESTIONS: Dict[str, Dict[str, str]] = {
    # Foreign words (Fremdwörter)
    "administration": {"simple": "Verwaltung", "category": "Fremdwort"},
    "implementieren": {"simple": "umsetzen", "category": "Fremdwort"},
    "implementation": {"simple": "Umsetzung", "category": "Fremdwort"},
    "evaluieren": {"simple": "prüfen", "category": "Fremdwort"},
    "evaluation": {"simple": "Prüfung", "category": "Fremdwort"},
    "konzept": {"simple": "Plan, Idee", "category": "Fremdwort"},
    "konzeption": {"simple": "Planung", "category": "Fremdwort"},
    "kommunikation": {"simple": "Gespräch, Austausch", "category": "Fremdwort"},
    "kommunizieren": {"simple": "sprechen, sich austauschen", "category": "Fremdwort"},
    "information": {"simple": "Auskunft, Nachricht", "category": "Fremdwort"},
    "informieren": {"simple": "mitteilen, sagen", "category": "Fremdwort"},
    "organisation": {"simple": "Gruppe, Verein", "category": "Fremdwort"},
    "organisieren": {"simple": "planen, vorbereiten", "category": "Fremdwort"},
    "dokumentation": {"simple": "Aufschreibung, Unterlagen", "category": "Fremdwort"},
    "dokumentieren": {"simple": "aufschreiben", "category": "Fremdwort"},
    "präsentation": {"simple": "Vorstellung, Vortrag", "category": "Fremdwort"},
    "präsentieren": {"simple": "vorstellen, zeigen", "category": "Fremdwort"},
    "diskussion": {"simple": "Gespräch, Besprechung", "category": "Fremdwort"},
    "diskutieren": {"simple": "besprechen", "category": "Fremdwort"},
    "akzeptieren": {"simple": "annehmen, einverstanden sein", "category": "Fremdwort"},
    "analysieren": {"simple": "untersuchen, prüfen", "category": "Fremdwort"},
    "optimieren": {"simple": "verbessern", "category": "Fremdwort"},
    "realisieren": {"simple": "verwirklichen, umsetzen", "category": "Fremdwort"},
    "ignorieren": {"simple": "nicht beachten", "category": "Fremdwort"},
    "tolerieren": {"simple": "dulden, erlauben", "category": "Fremdwort"},
    "integrieren": {"simple": "einbeziehen, aufnehmen", "category": "Fremdwort"},
    "koordinieren": {"simple": "abstimmen, planen", "category": "Fremdwort"},
    "korrigieren": {"simple": "verbessern, richtig machen", "category": "Fremdwort"},
    "kontrollieren": {"simple": "prüfen, überprüfen", "category": "Fremdwort"},
    "produzieren": {"simple": "herstellen, machen", "category": "Fremdwort"},
    "konstruieren": {"simple": "bauen, entwerfen", "category": "Fremdwort"},
    "funktionieren": {"simple": "arbeiten, gehen", "category": "Fremdwort"},
    "existieren": {"simple": "da sein, es gibt", "category": "Fremdwort"},
    "resultieren": {"simple": "sich ergeben", "category": "Fremdwort"},
    "initiieren": {"simple": "beginnen, starten", "category": "Fremdwort"},
    "definieren": {"simple": "festlegen, bestimmen", "category": "Fremdwort"},
    "identifizieren": {"simple": "erkennen, feststellen", "category": "Fremdwort"},
    "qualifizieren": {"simple": "befähigen", "category": "Fremdwort"},
    "quantifizieren": {"simple": "zählen, messen", "category": "Fremdwort"},
    "differenzieren": {"simple": "unterscheiden", "category": "Fremdwort"},
    "spezialisieren": {"simple": "sich auf etwas ausrichten", "category": "Fremdwort"},
    "generalisieren": {"simple": "verallgemeinern", "category": "Fremdwort"},
    "visualisieren": {"simple": "zeigen, darstellen", "category": "Fremdwort"},
    "maximieren": {"simple": "so groß wie möglich machen", "category": "Fremdwort"},
    "minimieren": {"simple": "so klein wie möglich machen", "category": "Fremdwort"},
    "garantieren": {"simple": "versprechen, sichern", "category": "Fremdwort"},
    "riskieren": {"simple": "wagen", "category": "Fremdwort"},
    "profitieren": {"simple": "Vorteil haben", "category": "Fremdwort"},
    "investieren": {"simple": "Geld ausgeben für", "category": "Fremdwort"},
    "finanzieren": {"simple": "bezahlen, Geld geben für", "category": "Fremdwort"},
    "kompensieren": {"simple": "ausgleichen", "category": "Fremdwort"},
    "demonstrieren": {"simple": "zeigen, vorführen", "category": "Fremdwort"},
    "illustrieren": {"simple": "zeigen, erklären", "category": "Fremdwort"},
    "motivieren": {"simple": "anspornen, ermutigen", "category": "Fremdwort"},
    "inspirieren": {"simple": "anregen", "category": "Fremdwort"},
    "frustrieren": {"simple": "enttäuschen", "category": "Fremdwort"},
    "irritieren": {"simple": "verwirren", "category": "Fremdwort"},
    "dominieren": {"simple": "beherrschen", "category": "Fremdwort"},
    "eliminieren": {"simple": "entfernen, beseitigen", "category": "Fremdwort"},
    "reduzieren": {"simple": "verringern, weniger machen", "category": "Fremdwort"},
    "regulieren": {"simple": "regeln, steuern", "category": "Fremdwort"},
    "stimulieren": {"simple": "anregen", "category": "Fremdwort"},
    "simulieren": {"simple": "nachahmen", "category": "Fremdwort"},
    # Technical/formal words (Fachsprache)
    "methodologie": {"simple": "Vorgehensweise", "category": "Fachsprache"},
    "infrastruktur": {"simple": "Grundausstattung", "category": "Fachsprache"},
    "kapazität": {"simple": "Fähigkeit, Möglichkeit", "category": "Fachsprache"},
    "kompetenz": {"simple": "Fähigkeit, Können", "category": "Fachsprache"},
    "komplexität": {"simple": "Schwierigkeit", "category": "Fachsprache"},
    "effizienz": {"simple": "Wirksamkeit", "category": "Fachsprache"},
    "effektivität": {"simple": "Wirksamkeit", "category": "Fachsprache"},
    "transparenz": {"simple": "Offenheit, Klarheit", "category": "Fachsprache"},
    "flexibilität": {"simple": "Anpassungsfähigkeit", "category": "Fachsprache"},
    "stabilität": {"simple": "Festigkeit, Beständigkeit", "category": "Fachsprache"},
    "priorität": {"simple": "Wichtigkeit, Vorrang", "category": "Fachsprache"},
    "qualität": {"simple": "Güte", "category": "Fachsprache"},
    "quantität": {"simple": "Menge", "category": "Fachsprache"},
    "kontinuität": {"simple": "Fortdauer", "category": "Fachsprache"},
    "intensität": {"simple": "Stärke", "category": "Fachsprache"},
    "aktivität": {"simple": "Tätigkeit", "category": "Fachsprache"},
    "produktivität": {"simple": "Leistung", "category": "Fachsprache"},
    "kreativität": {"simple": "Einfallsreichtum", "category": "Fachsprache"},
    "objektivität": {"simple": "Sachlichkeit", "category": "Fachsprache"},
    "subjektivität": {"simple": "persönliche Sicht", "category": "Fachsprache"},
    "realität": {"simple": "Wirklichkeit", "category": "Fachsprache"},
    "potenzial": {"simple": "Möglichkeit", "category": "Fachsprache"},
    "ressource": {"simple": "Mittel, Vorrat", "category": "Fachsprache"},
    "strategie": {"simple": "Plan, Vorgehen", "category": "Fachsprache"},
    "perspektive": {"simple": "Blickwinkel, Sicht", "category": "Fachsprache"},
    "dimension": {"simple": "Ausmaß, Größe", "category": "Fachsprache"},
    "konsequenz": {"simple": "Folge", "category": "Fachsprache"},
    "tendenz": {"simple": "Richtung, Neigung", "category": "Fachsprache"},
    "frequenz": {"simple": "Häufigkeit", "category": "Fachsprache"},
    "relevanz": {"simple": "Wichtigkeit, Bedeutung", "category": "Fachsprache"},
    "präsenz": {"simple": "Anwesenheit", "category": "Fachsprache"},
    "evidenz": {"simple": "Beweis, Nachweis", "category": "Fachsprache"},
    "kompetent": {"simple": "fähig, können", "category": "Fachsprache"},
    "effizient": {"simple": "wirksam, gut", "category": "Fachsprache"},
    "effektiv": {"simple": "wirksam", "category": "Fachsprache"},
    "relevant": {"simple": "wichtig, bedeutsam", "category": "Fachsprache"},
    "signifikant": {"simple": "bedeutsam, wichtig", "category": "Fachsprache"},
    "adäquat": {"simple": "angemessen, passend", "category": "Fachsprache"},
    "optimal": {"simple": "bestmöglich", "category": "Fachsprache"},
    "essenziell": {"simple": "wichtig, wesentlich", "category": "Fachsprache"},
    "fundamental": {"simple": "grundlegend", "category": "Fachsprache"},
    "elementar": {"simple": "grundlegend, einfach", "category": "Fachsprache"},
    "substanziell": {"simple": "wesentlich", "category": "Fachsprache"},
    "potenziell": {"simple": "möglich", "category": "Fachsprache"},
    "partiell": {"simple": "teilweise", "category": "Fachsprache"},
    "individuell": {"simple": "einzeln, persönlich", "category": "Fachsprache"},
    "kollektiv": {"simple": "gemeinsam, zusammen", "category": "Fachsprache"},
    "kontinuierlich": {"simple": "fortlaufend, ständig", "category": "Fachsprache"},
    "sukzessive": {"simple": "nach und nach", "category": "Fachsprache"},
    "simultan": {"simple": "gleichzeitig", "category": "Fachsprache"},
    "parallel": {"simple": "gleichzeitig, nebeneinander", "category": "Fachsprache"},
    "konträr": {"simple": "gegensätzlich", "category": "Fachsprache"},
    "analog": {"simple": "ähnlich, entsprechend", "category": "Fachsprache"},
    "konkret": {"simple": "genau, bestimmt", "category": "Fachsprache"},
    "abstrakt": {"simple": "nicht greifbar", "category": "Fachsprache"},
    "explizit": {"simple": "ausdrücklich, klar", "category": "Fachsprache"},
    "implizit": {"simple": "nicht direkt gesagt", "category": "Fachsprache"},
}


def get_suggestion(word: str) -> Optional[Dict[str, str]]:
    """Get suggestion for a complex word if available."""
    return COMPLEX_WORDS_WITH_SUGGESTIONS.get(word.lower())


def is_whitelisted(word: str) -> bool:
    """Check if a word is in the simple words whitelist."""
    return word.lower() in SIMPLE_WORDS_WHITELIST
